### ISSUE TITLE
Code cannot compile

### ISSUE THREAD

**Issue by akshit-sharma** [assimp/assimp_view#26]
**Describe the bug**
Your last [commit](https://github.com/assimp/assimp_view/commit/ec66676cffdf7b7e5056fd53085b5325b4086e91) removed files [main.cpp](https://github.com/assimp/assimp_view/blob/ec66676cffdf7b7e5056fd53085b5325b4086e91/CMakeLists.txt#L56) and [AssimpViewerApp.cpp](https://github.com/assimp/assimp_view/blob/ec66676cffdf7b7e5056fd53085b5325b4086e91/CMakeLists.txt#L53) from the src directory (required for compilation).

**To Reproduce**
1. Go to root of cloned directory.
2. Run ```cmake -B Build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON```
3. See error

**Expected behavior**
Code should compile

**Desktop (please complete the following information):**
 - OS: Linux (KUbuntu)
 - Browser N/A
 - Version N/A

**Additional context**

**Current Output**
```
CMake Error at CMakeLists.txt:62 (ADD_EXECUTABLE):
  Cannot find source file:

    src/AssimpViewerApp.cpp


CMake Error at CMakeLists.txt:62 (ADD_EXECUTABLE):
  No SOURCES given to target: assimp_view
```

Culprit seems to be this [commit](https://github.com/assimp/assimp_view/commit/ec66676cffdf7b7e5056fd53085b5325b4086e91).

**Comment by kimkulling** [comment]
Shall be fixed. Still experimental, but on a good way.
